service: baselime-pokedex

custom:
  region: eu-west-1

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 128
  stage: ${opt:stage}
  timeout: 30
  region: "${self:custom.region}"
  tracing: 
    lambda: true
  logRetentionInDays: 1
  versionFunctions: false
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'dynamodb:putItem'
          Resource: !GetAtt Table.Arn
functions:
  pokedex:
    handler: index.handler
    description: ${opt:stage} - gets a pokemon from the pokedex
    events:
      - http: 
          path: pokemons/{name}
          method: get 
          cors: true
          request: 
            parameters: 
              paths: 
                name: true
  seed:
    timeout: 900
    handler: seed.handler
    description: seeds the db

resources:
  Resources:
    Table:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${opt:stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
         
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH